apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker
  namespace: gic-wesago

spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checker
      
  template:
    metadata:
      labels:
        app: health-checker
    spec:
      containers:
      - name: health-check-container
        image: registry.deti/gic-wesago/health-checker:v1
        command: ["sh", "-c", "cp /scripts/script.sh /root; chmod +x /root/script.sh; ./root/script.sh"]
        imagePullPolicy: Always
        resources: {}
        env:
        - name: PSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: health-secret
              key: PSQL_PASSWORD
              optional: false
        # Mount volume for cluster config
        volumeMounts:
        - name: kube-config
          mountPath: /root/.kube/config
          subPath: CONFIG
        - name: health-check-script
          mountPath: /scripts
        - name: rsyslog-config
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
        - name: rsyslog-logs
          mountPath: /var/log/rsyslog
      
      - name: health-check-ingress
        image: registry.deti/gic-wesago/health-checker:v1
        command: ["sh", "-c", "cp /scripts/scriptO.sh /root; chmod +x /root/scriptO.sh; ./root/scriptO.sh"]
        imagePullPolicy: Always
        resources: {}
        # Mount volume for cluster config
        volumeMounts:
        - name: health-check-script
          mountPath: /scripts
        - name: rsyslog-config
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
        - name: rsyslog-logs
          mountPath: /var/log/rsyslog
      
      - name: rsyslog
        image: registry.deti/gic-wesago/rsyslog-server:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 514
          protocol: UDP
        - containerPort: 514
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: rsyslog-config
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
        - name: rsyslog-logs
          mountPath: /var/log/rsyslog
    
      # Volumes configuration
      volumes:
      - name: kube-config
        secret:
          secretName: health-secret
      - name: health-check-script
        configMap:
          name: health-check-script
      - name: rsyslog-config
        configMap:
          name: rsyslog-healthcheck-config
      - name: rsyslog-logs
        persistentVolumeClaim:
          claimName: rsyslog-healthcheck-pvc
  
