---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsyslog-healthcheck-pvc
  namespace: gic-wesago
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
