apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: gic-wesago
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access":"proxy",
          "editable": true,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": "http://kube-prometheus-1711023861-prometheus.default.svc:9090",
          "version": 1
        }
      ]
    }