{
 "title": "Nginx",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pods Running (App)",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"nginx-wesago\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts (App)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"nginx-wesago\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Running (Website)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"nginx-website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts (Website)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"nginx-website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods CPU Usage (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"nginx-wesago.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods CPU Usage (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"nginx-website.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Memory Usage (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"nginx-wesago-.*\", container=\"nginx-wesago\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Memory Usage (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"nginx-website-.*\", container=\"nginx-website\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Receive (Bytes) (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-wesago-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Receive (Bytes) (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-website-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Transmit (Bytes) (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-wesago-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Transmit (Bytes) (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-website-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Django",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"wesago-django\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"wesago-django\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\", container=\"wesago-django\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\", container=\"wesago-django\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods Network Receive (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods Network Transmit (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods fs Reads (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"gic-wesago\", container=\"wesago-django\", device=\"/dev/sda\"}[5m]))",
     "legendFormat": "Bytes read"
    }
   ]
  },
  {
   "title": "Django Pods fs Writes (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"gic-wesago\", container=\"wesago-django\", device=\"/dev/sda\"}[5m]))",
     "legendFormat": "Bytes write"
    }
   ]
  }
 ]
}
{
 "title": "Postgres",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"postgres\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"postgres\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"postgres-.*\", container=\"postgres\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"postgres-.*\", container=\"postgres\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Pods Network Receive (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"gic-wesago\", pod=~\"postgres-.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Pods Network Transmit (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"gic-wesago\", pod=~\"postgres.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Redis",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Redis Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"redis\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Pods Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"redis\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"sentinel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"sentinel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"redis-.*\", container=\"redis\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"sentinel-.*\", container=\"sentinel\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"redis-.*\", container=\"redis\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"sentinel-.*\", container=\"sentinel\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Persistent Volumes",
 "time": { "from": "2024-06-06T02:13:23.007Z", "to": "2024-06-06T03:13:23.007Z" },
 "panels": [
  {
   "title": "Persistent Volumes - Used %",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_available_bytes{namespace=\"gic-wesago\", persistentvolumeclaim!~\"rsyslog-.*\"}) / sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_capacity_bytes{namespace=\"gic-wesago\", persistentvolumeclaim!~\"rsyslog-.*\"})) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Rsyslog Persistent Volumes - Used %",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_available_bytes{namespace=\"gic-wesago\", persistentvolumeclaim=~\"rsyslog-.*\"}) / sum by (persistentvolumeclaim, namespace) (kubelet_volume_stats_capacity_bytes{namespace=\"gic-wesago\", persistentvolumeclaim=~\"rsyslog-.*\"})) * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}