---
apiVersion: v1
kind: Service
metadata:
  namespace: gic-wesago
  name: sentinel
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    name: sentinel
  selector:
    app: sentinel