---
apiVersion: v1
kind: Service
metadata:
  namespace: gic-wesago
  name: sentinel
spec:
  clusterIP: None
  ports:
  - port: 26379
    targetPort: 26379
    name: sentinel
  selector:
    app: sentinel