apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
  namespace: gic-wesago
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nginx-website
          image: registry.deti/gic-wesago/nginxwebsite:v1
          volumeMounts:
            # static files for website
            - name: static-files
              mountPath: /var/www/static
            # nginx config
            - name: nginx-website-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            requests:
              memory: "32Mi"
              cpu: "250m"
            limits:
              memory: "32Mi"
              cpu: "500m"
      volumes:
        # static files for website
        - name: static-files
          persistentVolumeClaim:
            claimName: react-pvc
        # nginx config
        - name: nginx-website-conf
          configMap:
            name: nginx-website-conf
            items:
               - key: nginx.conf
                 path: nginx.conf
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: nginx-website