apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
  namespace: gic-wesago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nginx-website
          image: registry.deti/gic-wesago/nginxstatic:v1
          volumeMounts:
            - name: static-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: static-files
          persistentVolumeClaim:
            claimName: react-pvc