{
 "title": "Django",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"wesago-django\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"wesago-django\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\", container=\"wesago-django\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\", container=\"wesago-django\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods Network Receive (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods Network Transmit (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"gic-wesago\", pod=~\"wesago-django-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Django Pods fs Reads (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"gic-wesago\", container=\"wesago-django\", device=\"/dev/sda\"}[5m]))",
     "legendFormat": "Bytes read"
    }
   ]
  },
  {
   "title": "Django Pods fs Writes (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"gic-wesago\", container=\"wesago-django\", device=\"/dev/sda\"}[5m]))",
     "legendFormat": "Bytes write"
    }
   ]
  }
 ]
}