{
 "title": "Nginx",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Pods Running (App)",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"nginx-wesago\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts (App)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"nginx-wesago\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Running (Website)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"nginx-website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Restarts (Website)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"nginx-website\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods CPU Usage (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"nginx-wesago.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods CPU Usage (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"nginx-website.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Memory Usage (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"nginx-wesago-.*\", container=\"nginx-wesago\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Memory Usage (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"nginx-website-.*\", container=\"nginx-website\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Receive (Bytes) (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-wesago-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Receive (Bytes) (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-website-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Transmit (Bytes) (App)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-wesago-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Pods Network Transmit (Bytes) (Website)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"gic-wesago\", pod=~\"nginx-website-.*\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}