{
 "title": "Redis",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Redis Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"redis\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Pods Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"redis\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=\"gic-wesago\", container=\"sentinel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods Restarts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"gic-wesago\", container=\"sentinel\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"redis-.*\", container=\"redis\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"gic-wesago\", pod=~\"sentinel-.*\", container=\"sentinel\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"redis-.*\", container=\"redis\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sentinel Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"gic-wesago\", pod=~\"sentinel-.*\", container=\"sentinel\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}