---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: gic-wesago
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: config
        image: registry.deti/gic-wesago/postgres:v1
        command: [ "bash", "-c" ]
        args:
        - |
          cp /temp-config/pg_hba.conf /config/pg_hba.conf
          cp /temp-config/postgresql.conf /config/postgresql.conf
          cp /temp-config/pg_ident.conf /config/pg_ident.conf
          
          mkdir -p /data/archive && chown -R 999:999 /data/archive

          if [ "$(hostname)" = "postgres-0" ]; then
            #create archive directory
            echo "host     replication     replicationUser         0.0.0.0/0        trust" >> /config/pg_hba.conf

            # Write the replication settings to the files
            echo "#replication" >> /config/postgresql.conf
            echo "wal_level = replica" >> /config/postgresql.conf
            echo "archive_mode = on" >> /config/postgresql.conf
            echo "archive_command = 'test ! -f /data/archive/%f && cp %p /data/archive/%f'" >> /config/postgresql.conf
            echo "max_wal_senders = 3" >> /config/postgresql.conf
          else
            # Check if /data/pgdata exists, if it exists, remove it
            # if [ -d /data/pgdata ]; then
            #   rm -rf /data/pgdata
            # fi

            # Check if /data/pgdata exists, if it not exists, run the basebackup
            if [ ! -d /data/pgdata ]; then
              pg_basebackup -h postgres-0.postgres.gic-wesago.svc.cluster.local -p 5432 -U replicationUser -D /data/pgdata -Fp -Xs -R
            fi
          fi
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
        - name: config
          mountPath: /config
          readOnly: false
        - name: temp-config
          mountPath: /temp-config
          readOnly: false

      containers:
      - name: postgres
        image: registry.deti/gic-wesago/postgres:v1
        args: ["-c", "config_file=/config/postgresql.conf"]
        ports:
        - containerPort: 5432
          name: database
        env:
        - name: PGDATA
          value: "/data/pgdata"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
              optional: false
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: false
        - name: data
          mountPath: /data
          readOnly: false
      
      volumes:
      - name: config
        emptyDir: {}
      - name: temp-config
        configMap:
          name: postgres
          
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
