apiVersion: batch/v1
kind: Job
metadata:
  name: wesago-createsuperuser
  namespace: gic-wesago
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: 100

  template:
    spec:
      containers:
        - name: createsuperuser-container
          image: registry.deti/gic-wesago/wesago-django:v1
          command: ["python", "manage.py", "createsuperuser", "--no-input", "--username", "$(DJANGO_SUPERUSER_USERNAME)", "--email", "$(DJANGO_SUPERUSER_EMAIL)", "--password", "$(DJANGO_SUPERUSER_PASSWORD)"]
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: wesago-cm
          - secretRef:
              name: wesago-secret
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static"
              name: static
            - mountPath: "/app/media"
              name: media
            - mountPath: "/app/avatargallery"
              name: avatargallery
            - mountPath: "/app/theme"
              name: theme
            - mountPath: "/var/log/rsyslog"
              name: rsyslog-logs
              
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: wesago-static-pvc
        - name: media
          persistentVolumeClaim:
            claimName: wesago-media-pvc
        - name: avatargallery
          persistentVolumeClaim:
            claimName: wesago-avatargallery-pvc
        - name: theme
          persistentVolumeClaim:
            claimName: wesago-theme-pvc
        - name: rsyslog-logs
          persistentVolumeClaim:
            claimName: rsyslog-django-pvc

      restartPolicy: OnFailure
  backoffLimit: 3
