apiVersion: apps/v1
kind: Deployment
metadata:
  name: wesago-django
  namespace: gic-wesago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wesago-django
  template:
    metadata:
      labels:
        app: wesago-django
    spec:
      containers:
      - name: wesago-django
        image: registry.deti/gic-wesago/wesago-django:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        envFrom:
        - configMapRef:
            name: wesago-cm
        - secretRef:
            name: wesago-secret

        volumeMounts:
        - name: media
          mountPath: /app/media
        - name: static
          mountPath: /app/static
        - name: avatargallery
          mountPath: /app/avatargallery
        - name: theme
          mountPath: /app/theme

      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: wesago-media-pvc
      - name: static
        persistentVolumeClaim:
          claimName: wesago-static-pvc
      - name: avatargallery
        persistentVolumeClaim:
          claimName: wesago-avatargallery-pvc
      - name: theme
        persistentVolumeClaim:
          claimName: wesago-theme-pvc