apiVersion: batch/v1
kind: Job
metadata:
  name: wesago-db-migrations
  namespace: gic-wesago
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: 60

  template:
    spec:
      containers:
        - name: wesago-django
          image: registry.deti/gic-wesago/wesago-django:v1
          command: ['python', 'manage.py', 'migrate', '--run-syncdb']
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
          - configMapRef:
              name: wesago-cm
          - secretRef:
              name: wesago-secret
          volumeMounts:
            - mountPath: "/var/log/rsyslog"
              name: rsyslog-logs
      volumes:
        - name: rsyslog-logs
          persistentVolumeClaim:
            claimName: rsyslog-django-pvc

      restartPolicy: OnFailure
  backoffLimit: 15
