apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-server
  namespace: gic-wesago
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsyslog-server
  template:
    metadata:
      labels:
        app: rsyslog-server
    spec:
      containers:
      - name: rsyslog-server
        image: registry.deti/gic-wesago/rsyslog-server:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 514
          protocol: UDP
        - containerPort: 514
          protocol: TCP
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        volumeMounts:
        - name: rsyslog-config
          mountPath: /etc/rsyslog.conf
          subPath: rsyslog.conf
        - name: rsyslog-logs
          mountPath: /var/log/rsyslog

      volumes:
      - name: rsyslog-config
        configMap:
          name: rsyslog-server-config
      - name: rsyslog-logs
        persistentVolumeClaim:
          claimName: rsyslog-server-pvc
